# System setup
system:
  name: Dummy Setup
  connection_file: configuration/connection_file.xml
  # shelfs were the the boards are inserted
  shelfs:
    - id: shelf-1
      location: SGxFy
    - id: shelf-2
      location: SGxFy
  # boards connected to the system
  # should have the same IDs as in the connection_file
  boards:
    - id: board-A
      shelf: shelf1
      slot: 1
      type: concentrator
    - id: board-B
      shelf: shelf1
      slot: 2
      type: fan-out
    - id: board-C
      shelf: shelf2
      slot: 1
      type: fan-out
  # data and clock managers (AMC13, DTH, ...)
  # should have the same id as in the connection_file
  data-clock-manager:
    - id: dcm-1
      shelf: shelf-1
      slot: 13
    - id: dcm-2
      shelf: shelf-2
      slot: 13
